spring:
      output:
            ansi:
                  enabled: ALWAYS
      application:
            name: Spring Boot Restful Api
            version: 1.0.0
      datasource:
            url: jdbc:postgresql://localhost:5432/mobiledb
            username: postgres
            password: 1234
      jpa:
            open-in-view: false
            defer-datasource-initialization: true
            generate-ddl: false
            hibernate:
                  ddl-auto: update
      sql:
            init:
                  mode: always
                  continue-on-error: false
                  schema-locations:
                        - classpath:/schema.sql



